version: '3'

services:
  backend:
    build: ./backend/docker
    container_name: ads_backend
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
        - ./backend:/var/www/html
        - ./backend/docker/nginx_log:/var/log/nginx
        - ./backend/docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
        - ./backend/docker/config/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - mysql
    networks:
      - backend_network

  mysql:
    image: mysql
    container_name: ads_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./backend/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lyvantanh2002
    networks:
      - backend_network

  frontend:
    build: ./frontend
    container_name: ads_frontend
    working_dir: /var/www/html
    ports:
      - "3000:3000"
    networks:
      - backend_network

networks:
  backend_network:
